name: facebook/metro/build-and-deploy
on:
  push:
    branches:
    - main
jobs:
  run-js-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: 18.12
        cache: yarn
    - name: Install Dependencies
      run: npm install --force flow-bin
    - run: yarn typecheck
    - run: yarn typecheck-ts
    - run: yarn lint
    - run: yarn test-smoke
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: 18.12
        cache: yarn
    - name: Install Dependencies
      run: npm install --force @babel/core
    - run: yarn test-coverage
    - name: Download Codecov Uploader
      run: "./.circleci/scripts/install_codecov.sh"
    - name: Upload coverage results
      run: "./codecov -t ${{ secrets.CODECOV_TOKEN }} -f ./coverage/coverage-final.json"
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.12, 20.2 ]
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: "./.github/actions/install_and_run_tests"
  test-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/upload-artifact@v4.0.0
      with:
        path: reports/
    - uses: actions/setup-node@v4
      with:
        node-version: 18.12
        cache: yarn
    - name: Install Dependencies
      run: npm install --force --save-dev jest
    - name: Run Jest tests
      run: yarn jest --ci --maxWorkers 4 --reporters=default --reporters=jest-junit
  publish-to-npm:
    if: |
      startsWith(github.ref, 'refs/tags/v') && (
        contains(github.ref, '-alpha') ||
        contains(github.ref, '-beta') ||
        contains(github.ref, '-rc') ||
        (endsWith(github.ref, '.0') && contains(github.ref, '-'))
      )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-node@v4
      with:
        node-version: 18.12
        cache: yarn
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
    - name: Infer dist-tag and run npm run publish
      run: "./.circleci/scripts/publish.sh"
    - run: rm ~/.npmrc
